// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKLrK7kzvVijO_8dAi_XZ4RPwgOkJLJuQ',
    appId: '1:605768864743:web:257624faf7e08b3a1ce342',
    messagingSenderId: '605768864743',
    projectId: 'food-store-web-app',
    authDomain: 'food-store-web-app.firebaseapp.com',
    storageBucket: 'food-store-web-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-cmzWcUzmRmpw9m1RF9cBf9a1SCWsLyY',
    appId: '1:605768864743:android:eddd2f969559e3c01ce342',
    messagingSenderId: '605768864743',
    projectId: 'food-store-web-app',
    storageBucket: 'food-store-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRt2OIa6ffUeGBXLzGTHBdMUGWRWWzEVI',
    appId: '1:605768864743:ios:6e74020b6fd677901ce342',
    messagingSenderId: '605768864743',
    projectId: 'food-store-web-app',
    storageBucket: 'food-store-web-app.appspot.com',
    iosClientId: '605768864743-sal81c4jcfroluagdplugeknou0es3sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRt2OIa6ffUeGBXLzGTHBdMUGWRWWzEVI',
    appId: '1:605768864743:ios:6e74020b6fd677901ce342',
    messagingSenderId: '605768864743',
    projectId: 'food-store-web-app',
    storageBucket: 'food-store-web-app.appspot.com',
    iosClientId: '605768864743-sal81c4jcfroluagdplugeknou0es3sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullstore',
  );
}
